### PR TITLE
Fixed ISO8601 format issue; Updated documentation and Makefile

### PR DESCRIPTION
**Pull request by blagerweij**
When using the sso fetcher, I ran into issues with timezones. This should fix the issue with UTC formatting of ISO8601 dates.
Also updated the makefile, and fixed a documentation issue (credential_process should go into the `~/.aws/credentials` file, not `~/.aws/config`

### CODE REVIEW

**Comment by flyinprogrammer** [comment]
thanks for this - you should see it released

**Comment by flyinprogrammer** [comment]
also you should know, the `credential_process` value in a `profile` definition should be placed in the config file - according to their docs: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

**Comment by blagerweij** [comment]
Weird, the Java SDK uses the `~/.aws/credentials` file, which is why I updated the docs. Thanks for merging

**Comment by blagerweij** [comment]
I just checked: AWS CLI v2 also uses the credentials file. Also the GO SDK seems to use that. If you could double check this, then we might need to update the README. For me it's working; I'm using Java and Terraform (Golang).

**Comment by flyinprogrammer** [comment]
> I just checked: AWS CLI v2 also uses the credentials file.

where do you see this?

**Comment by blagerweij** [comment]
Never mind my comments, I just noticed the following: we can either use the 'config' file with the 'profile xxxx' section, or use the 'credentials' file without the 'profile ' prefix.

See also https://github.com/aws/aws-sdk-go/blob/b2eca0161ed7c7fd947624e8c49ef16411088d8b/aws/credentials/processcreds/testdata/shconfig.ini and https://github.com/aws/aws-sdk-go/blob/b2eca0161ed7c7fd947624e8c49ef16411088d8b/aws/credentials/processcreds/testdata/shcred.ini

**Pull request merged**
